# Site settings
title: Wydawnictwo Bernardinum
description: |
  Tu powstaje nowa strona  
  Wydawnictwa Bernardinum  
owner: Wydawnictwo Bernardinum
first_published: 
email: 
baseurl: "" 
url: ""
logo_url: /images/Logo-Bernardinum-480px-white-web.png
social:
  twitter: 
  github: 
  linkedin-square: 
  facebook-official: 
formspark_id: 

exclude: [
    Gemfile,
    Gemfile.lock,
    .gitignore,
    README,
    LICENSE,
    spectral_jekyll_theme.gemspec
]

markdown: kramdown
#sass:
#  style: compressed
