# Site settings
title: Wydawnictwo Bernardinum
description: |
  Tu powstaje nowa strona  
  Wydawnictwa Bernardinum  
owner: Wydawnictwo Bernardinum
first_published: 
email: 
baseurl: "" 
url: "/noweteraz.bernardinum-com-pl"
logo_url: /images/Logo-Bernardinum-480px-white-web.png
social:
  twitter: 
  github: 
  linkedin-square: 
  facebook-official: 
formspark_id: 


markdown: kramdown
#sass:
#  style: compressed
